apiVersion: v1
kind: Pod
metadata:
    name: building-apps-pod
    labels:
        app: kubeacademy
spec:
    containers:
    - name : building-apps-container
      image : camaranto/building-apps:0.1